// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:games_list/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CollectionItemAdapter());
    registerAdapter(CollectionTypeAdapter());
    registerAdapter(SearchHistoryWordAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CollectionItemAdapter());
    registerAdapter(CollectionTypeAdapter());
    registerAdapter(SearchHistoryWordAdapter());
  }
}
